from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyfdl.Rectangle import Rectangle


class TestRectangle(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 08 February 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testLTRBSimple(self):

        expectedRectangle: Rectangle = Rectangle(x=100, y=100, width=100, height=100)

        actualRectangle: Rectangle = Rectangle.FromLTRB(left=100, top=100, right=200, bottom=200)

        self.assertEqual(expectedRectangle, actualRectangle, 'Should be functionally the same')

    def testLTRBComplex(self):

        expectedRectangle: Rectangle = Rectangle(x=62, y=47, width=76, height=175)

        actualRectangle: Rectangle = Rectangle.FromLTRB(left=62, top=47, right=138, bottom=222)

        self.assertEqual(expectedRectangle, actualRectangle, 'Should be functionally the same')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestRectangle))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
